# ----------------------------------------------------------------------------
# Dockerfile - a Keycloak image that includes the SMART on FHIR extensions.
#
# SPDX-License-Identifier: Apache-2.0
# ----------------------------------------------------------------------------

# Build Stage
#FROM maven:3.8.3-openjdk-11-slim AS builder
FROM maven:3.9.4-eclipse-temurin-21-alpine AS builder

ARG target_realm=example
ARG target_realm_display_name="Example SMART on FHIR Realm."
ARG terraform_client_id=terraform
ARG terraform_client_secret

# Set the working directory in the container
WORKDIR /app

# Copy the Maven configuration and project files
COPY smart-on-fhir-spi/pom.xml .
COPY smart-on-fhir-spi/src src
COPY keycloak keycloak

# Copy the theme files
COPY smart-theme/pom.xml ./smart-theme/
COPY smart-theme/src ./smart-theme/src
# Build the theme
RUN mvn -B -f smart-theme/pom.xml clean package

# Build the application JAR
RUN mvn -B clean package -DskipTests

# Make the script executable
RUN chmod +x keycloak/bin/terraform-realm-admin.sh

# Modify the realm.json file to contain ENV variables for realm name and terraform client secret
# sed -i does not work in alpine, so we have to use a temporary file...
RUN cd /app/keycloak/import && sed "s/{{place_realm_name_here}}/$target_realm/g" realm-template.json > r1.json
RUN cd /app/keycloak/import && sed "s/{{place_realm_display_name_here}}/$target_realm_display_name/g" r1.json > r2.json
RUN cd /app/keycloak/import && sed "s/{{place_terraform_client_name_here}}/$terraform_client/g" r2.json > r3.json
RUN cd /app/keycloak/import && sed "s/{{place_terraform_client_secret_here}}/$terraform_client_secret/g" r3.json > realm.json
RUN cd /app/keycloak/import && rm r1.json r2.json r3.json

# Package Stage - add to an official Keycloak image
FROM quay.io/keycloak/keycloak:24.0.5-0

# need this set so we can use it in entrypoint to 
# apply realm admin rights to the terraform client.
ENV KEYCLOAK_TARGET_REALM=$KEYCLOAK_TARGET_REALM
ENV KEYCLOAK_PORT=8080

# Set the working directory in the container
WORKDIR /opt/keycloak/

# Copy the JAR file from the builder stage to the final image
COPY --from=builder /app/keycloak/import/realm.json ./data/import/realm.json
# Copy the script that sets the realm admin roles for the terraform client
COPY --from=builder /app/keycloak/bin/terraform-realm-admin.sh ./bin/terraform-realm-admin.sh
COPY --from=builder /app/target/deploy/*.jar ./providers/

# Copy the theme files
COPY --from=builder /app/smart-theme/target/*.jar ./providers/

# Expose the port if needed
EXPOSE $KEYCLOAK_PORT

# Start Keycloak with the import-realm optin to load in the SMART on FHIR realm
CMD ["start-dev", "--import-realm", "--log-level=info", "--features=token-exchange,authorization,admin-fine-grained-authz"]