name: Build and Publish Image

on:
  workflow_dispatch:
  push:
    branches: 
      - main
    tags:
     - 'v*'  # triggers on tag starting with 'v'
    paths-ignore:
      - '.github/workflows/**'
      - 'docs/**'
      - '*.md'
      - '.vscode/**'

env:
  REGISTRY_URL: "https://registry.digitalocean.com/zedwerks"
  REGISTRY: registry.digitalocean.com/zedwerks
  IMAGE_NAME: keycloak-smart-fhir
  KEYCLOAK_TERRAFORM_CLIENT_SECRET: ${{ secrets.KEYCLOAK_TERRAFORM_CLIENT_SECRET }}

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Run tests
        run: echo "Tests passed"
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build .
  publish:
    name: Publish Image to DO Registry
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived token
        run: doctl registry login --expiry-seconds 600

      - name: Extract short SHA for tagging image
        id: vars
        run: echo "::set-output name=short_sha::${GITHUB_SHA::8}"

      - name: Prune up older Docker images
        env:
          IMAGES_TO_KEEP: 5
          REGISTRY: ${{ env.REGISTRY }}
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        run: |
          IMAGE_LIST=$(doctl registry repository list-manifests $REGISTRY --access-token $DIGITALOCEAN_ACCESS_TOKEN --interactive false -o text | sort -k2 | head -n -$IMAGES_TO_KEEP)
          echo $IMAGE_LIST
          if [ -z "$IMAGE_LIST" ]; then
            echo "No images to delete"
            exit 0
          fi
          echo "$IMAGE_LIST" | while read -r DIGEST UPDATED_AT; do
            echo "Deleting image with digest= $DIGEST updated=$UPDATED_AT"
            doctl registry repository delete-manifest $REGISTRY $DIGEST --access-token $DIGITALOCEAN_ACCESS_TOKEN --force --verbose --interactive false
          done

      - name: Docker login
        run: docker login ${{ env.REGISTRY }}

      - name: Build Docker image
        run: docker build . -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.short_sha }} -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Push Docker image to DigitalOcean Container Registry
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.short_sha }}

      - name: Push 'latest' Docker image to DigitalOcean Container Registry
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
