name: Maven Deploy to GitHub Packages

on:
  push:
    tags:
      - 'v*'  # Triggers only on version tags like v1.0.0
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # Required to publish to GitHub Packages

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          server-id: github  # Must match <server><id> in pom.xml
          settings-path: smart-on-fhir-spi

      - name: Set up Maven settings.xml
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.GH_PACKAGES_PAT }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Run Maven Install
        working-directory: smart-on-fhir-spi
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Version is: $VERSION"
          echo "Building smart-on-fhir-spi with version $VERSION"
          mvn install -DskipTests
          cp ~/.m2/repository/com/zedwerks/keycloak-smart-on-fhir/$VERSION/*.pom ./target/*.pom
          ls -l ./target/*.pom

      - name: Build and Deploy to GitHub Packages
        working-directory: smart-on-fhir-spi
        run: |
          mvn deploy -X -DskipTests -DaltDeploymentRepository=github::https://maven.pkg.github.com/zedwerks
