name: Maven Deploy to GitHub Packages

on:
  push:
    tags:
      - 'v*'  # Triggers only on version tags like v1.0.0
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # Required to publish to GitHub Packages

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          server-id: github  # Must match <server><id> in pom.xml
          #settings-path: ${{ github.workspace }}/smart-on-fhir-spi
          settings-path: ~/.m2  # use Maven's default
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Maven settings.xml
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.GITHUB_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF

     # - name: Configure Maven
     #   working-directory: ${{ github.workspace }}/smart-on-fhir-spi
     ###   run: |
      #    mkdir -p ~/.m2
       #   echo "<settings><servers><server><id>github</id><username>${GITHUB_ACTOR}</username><password>${{ secrets.GITHUB_TOKEN }}</password></server></servers></settings>" > ~/.m2/settings.xml

      - name: Build and Deploy to GitHub Packages
        working-directory: ${{ github.workspace }}/smart-on-fhir-spi
        run: |
          mvn clean package
          mvn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
