name: "Terraform Apply"

on:
  workflow_dispatch: # Allows manually triggering the workflow
    inputs:
      target_environment:
        description: "Target Environment"
        required: true
        default: "demo"
jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target_environment }}
    env:
      ENVIRONMENT: ${{ inputs.target_environment }}
      AWS_ACCESS_KEY_ID: ${{ secrets.DO_SPACES_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SPACES_SECRET_KEY }}
      KEYCLOAK_HOSTNAME_URL: ${{ vars.KEYCLOAK_HOSTNAME_URL }}
      KEYCLOAK_TARGET_REALM: ${{ vars.KEYCLOAK_TARGET_REALM }}
      KEYCLOAK_TERRAFORM_CLIENT_ID: ${{ vars.KEYCLOAK_TERRAFORM_CLIENT_ID }}
      KEYCLOAK_TERRAFORM_CLIENT_SECRET: ${{ secrets.KEYCLOAK_TERRAFORM_CLIENT_SECRET }}
      TF_VAR_keycloak_terraform_client_secret: ${{ secrets.KEYCLOAK_TERRAFORM_CLIENT_SECRET }}
      TF_VAR_keycloak_realm: ${{ vars.KEYCLOAK_TARGET_REALM }}
      TF_VAR_keycloak_terraform_client_id: ${{ vars.KEYCLOAK_TERRAFORM_CLIENT_ID }}
      TF_VAR_keycloak_base_url: ${{ vars.KEYCLOAK_HOSTNAME_URL }}
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Override Backend Configuration"
        working-directory: ./example/terraform
        run: |
          rm -f backend.tf || true
          cp environments/$ENVIRONMENT/backend.tf backend.tf

      - name: "Set up Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5 # Use your required Terraform version

      - name: "Terraform Init"
        env:
          ENVIRONMENT: ${{ inputs.target_environment }}
        working-directory: ./example/terraform
        run: |
          terraform init \
            --upgrade \
            -var-file=environments/$ENVIRONMENT/terraform.tfvars

      - name: "Terraform Apply"
        working-directory: ./example/terraform
        run: |
          terraform apply \
            -auto-approve -compact-warnings -var-file=./environments/$ENVIRONMENT/variables.tfvars
